include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    dead_code: error
    unused_element: warning
    unused_field: warning
    unused_local_variable: warning
    deprecated_member_use: error
linter:
  rules:
    - close_sinks
    - cancel_subscriptions
